### ISSUE TITLE
An error in some examples

### ISSUE THREAD

**Issue by EldersJavas** [tinne26/etxt#1]
hello, I found an error report

Like this,
https://github.com/tinne26/etxt/blob/99cc49a4b6cc88498f02f1f43c26e2422cda29f2/examples/gtxt/direction_bidi/main.go#L96-L98

it will report:
```bash
.\main.go:104:21: cannot use outImage (variable of type *image.RGBA) as type *ebiten.Image in argument to renderer.SetTarget
```

**Comment by tinne26** [comment]
Hey, sorry I didn't get back to you earlier, busy with the game jam and all that!

As mentioned in the [readme](https://github.com/tinne26/etxt#can-i-use-this-package-without-ebitengine), this package can be used _with_ or _without_ Ebitengine. In this case, you most likely tried to execute the program without `-tags gtxt`, which is necessary as this example isn't based on Ebitengine. For more info, you can check the readme in the [examples](https://github.com/tinne26/etxt/tree/main/examples) folder. There it mentions that all `gtxt` examples have to be executed with `-tags gtxt`.

The most misleading part is that both are compatible fairly often, so it's easy to be bitten by this.
