### ISSUE TITLE
ParseEmbedFontFrom accepts *embed.FS

### ISSUE THREAD

**Issue by sedyh** [tinne26/etxt#3]
Hello. This is a trifle, but is there a specific reason for accepting *embed.FS and not embed.FS in ParseEmbedFontFrom func? 
It still keeps a pointer inside. By default it is usually passed by value.

```
https://pkg.go.dev/embed

import "embed"

//go:embed hello.txt
var f embed.FS
data, _ := f.ReadFile("hello.txt")
print(string(data))
```

**Comment by tinne26** [comment]
Thanks for the report. Yeah, there's no particular reason, it looks like it should indeed be passed by value. I have other changes to make with the release of Ebitengine v2.4.0, so I'll fix it and tag a new version in a few days.
