### ISSUE TITLE
`go mod vendor` results in error when etxt is imported

### ISSUE THREAD

**Issue by Kintar** [tinne26/etxt#4]
Attempting to use the `go mod vendor` command fails when etxt is used. The error message "go: pattern test_font.ttf: no matching files found" is displayed, causing the vendoring process to abort in an unusable state.

For reproduction, I've created a very simple project consisting of a single font file and the etxt library. The application uses FontLibrary to read the fonts in the 'fonts' subfolder and list their names, and serves well to show the error.

* Clone this project : https://github.com/Kintar/etxt_error_example
* Execute `go run main.go` to see a list of the fonts included in the fonts directory
* Execute `go mod vendor` to see the error message
* Note that the application will no longer compile

**Comment by Kintar** [comment]
Update : I've identified the issue using my fork of the project at github.com/Kintar/etxt. The problem is that `font_test.go` references the nonexistent test_font.ttf. Adding a test_font.ttf to the repository or disabling the (nonfunctional) test file resolves the issue.

**Comment by tinne26** [comment]
I was aware of this, but the font is *definitely not* non-functional. If you run `run_tests.sh` or any form of `go test -tags gtxt ./...` and you don't have `test_font.ttf`, you will get something like this among the results:
> 2022/12/24 08:55:45 etxt requires '../test_font.ttf' file to run benchmarks

This is clearly visible at the init function of `font_test.go`. Good tests are critical for a library like this, and I want them to be in the repository.

I understand the issue with `go mod vendor`, but don't know any clean way to solve it. Golang's `x/font/` has multiple bugs that arise from the fact that they don't want to include fonts in the repositories (neither do I), but then still go ahead with rather lacking and incomplete testing.

The options are:
- Forking the project without any tests.
- Forking the project with the added `test_font.ttf`.
- Myself adding `test_font.ttf` directly to the project for the testing so nothing will fail.
- Maybe build tags can be used? I have to look into this.

If you have any other idea let me know.

**Comment by tinne26** [comment]
I have added an extra `test` build tag to tests so they won't interfere with `go mod vendor`. I'm still in the middle of new changes for adding shaders, so I'll release this in v0.0.9 when I also have shaders ready.

**Comment by Kintar** [comment]
No other ideas, your analysis of options matches mine. And I agree that tests are important, which is another question I had. I didn't see anything in the README about specific test flags. When running a basic `go test ./...`, I get one compilation error and a bunch of "no test files" responses, but no passed tests:

```bash
$ go test ./...
# github.com/tinne26/etxt/examples/gtxt/each_font
examples/gtxt/each_font/main.go:69:21: cannot use outImage (variable of type *image.RGBA) as type *ebiten.Image in argument to renderer.SetTarget
# github.com/tinne26/etxt/examples/ebiten/cutout
examples/ebiten/cutout/main.go:67:37: mask.Image undefined (type *ebiten.Image has no field or method Image)
?   	github.com/tinne26/etxt	[no test files]
?   	github.com/tinne26/etxt/ecache	[no test files]
?   	github.com/tinne26/etxt/efixed	[no test files]
?   	github.com/tinne26/etxt/eglyr	[no test files]
?   	github.com/tinne26/etxt/emask	[no test files]
?   	github.com/tinne26/etxt/emetric	[no test files]
?   	github.com/tinne26/etxt/esizer	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/all_glyphs	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/colorful	[no test files]
```

And when using the `-tags gtxt` tag you mentioned, I get more output, but still no passing tests:

```bash
$ go test -tags gtxt ./...
?   	github.com/tinne26/etxt	[no test files]
?   	github.com/tinne26/etxt/ecache	[no test files]
?   	github.com/tinne26/etxt/efixed	[no test files]
?   	github.com/tinne26/etxt/eglyr	[no test files]
?   	github.com/tinne26/etxt/emask	[no test files]
?   	github.com/tinne26/etxt/emetric	[no test files]
?   	github.com/tinne26/etxt/esizer	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/all_glyphs	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/colorful	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/elastic_sizer	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/faux_styles	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/hello_world	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/hover_shadow	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/rng_shape	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/select_rect_viz	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/shaking	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/typewriter	[no test files]
?   	github.com/tinne26/etxt/examples/ebiten/wrap	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/aligns	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/debug_glyph	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/each_font	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/font_library	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/hello_world	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/mirror	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/mix_modes	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/outline	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/outline_cheap	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/pattern	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/quantization	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/rainbow	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/rect_size	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/shape	[no test files]
?   	github.com/tinne26/etxt/examples/gtxt/sizer_expand	[no test files]
```

What am I missing about running tests in this project? I'd love to be an actual useful contributor instead of a leech with annoying requests. ;)

**Comment by Kintar** [comment]
Well, I see if I'd read your message instead of skimming it, there is a run_tests.sh file. :facepalm:  Still, not quite what I was expecting:

```bash
$ sh run_tests.sh 
# github.com/tinne26/etxt
font_test.go:10:12: pattern test_font.ttf: no matching files found
FAIL	github.com/tinne26/etxt [setup failed]
ok  	github.com/tinne26/etxt/ecache	1.005s	coverage: 90.0% of statements
ok  	github.com/tinne26/etxt/efixed	0.001s	coverage: 81.8% of statements
2022/12/25 19:38:22 etxt requires '../test_font.ttf' file to run benchmarks
FAIL	github.com/tinne26/etxt/emask	0.002s
FAIL
```

**Comment by tinne26** [comment]
You still need `test_font.ttf` and `test_font2.ttf` in order to run the tests, which is the only part that should be failing for you, and is mentioned in comments in the `run_tests.sh` script. What's failing is actually the embedding process, which indeed prevents the program from reaching `init` and actually provide a clearer error. I'm restructuring tests and setting up an empty `test/fonts/` folder so embed can never fail, and then I can check if the expected fonts are there or not and run the tests partially even if something is missing. Also documenting how everything is run. I'm also separating benchmarks from tests and a few other minor details. It will be ready in a few days. I have it all working already but I have to figure out what structure I like best.

**Comment by tinne26** [comment]
Anyway, in case you missed it, `go mod vendor` should be working with the latest commit, so you don't really need to bother with all this, which is why I closed the issue. I'll make sure to keep it working in the future even if I make further changes to testing.

**Comment by tinne26** [comment]
Instructions for testing are now explicitly available at https://github.com/tinne26/etxt/blob/main/test/README.md.
