### ISSUE TITLE
feature request: allow easily saving and restoring state

### ISSUE THREAD

**Issue by tinne26** [tinne26/etxt#9]
Idea suggested by @kettek, mimicking html canvas `save()` and `restore()` methods. Here's an API prototype:
```Golang
// Registers a new restore point for the renderer's state. You can jump
// back to the most recently memorized point with [RendererUtils.Rewind]().
// 
// The memorized state includes the following properties:
//  - Align, color, size, scale, blend mode, main font, rasterizer,
//    sizer and quantization.
// Notably, custom rendering function, secondary fonts and
// cache handler are not memorized.
//
// For improved safety when using renderer state restore points, you
// may want to consider [RendererUtils.AssertMaxRestorePoints]().
func (self *RendererUtils) Memorize() {
	// ...
}

// Jumps back to the previous restore point registered with
// [RendererUtils.Memorize]() and removes it after restoring
// the renderer's state.
//
// If the restore points stack is empty and no rewinding is
// possible, this function will return false.
func (self *RendererUtils) Rewind() bool {
	// ...
}

// Panics when the size of the restore points stack exceeds
// the given value. Restore points are created through
// [RendererUtils.Memorize]().
// 
// There are two main ways to use this function:
//  - Regularly asserting that the number of restore points
//    stay below a value that you never expect to reach (e.g.,
//    64) in order to prevent memory leaks.
//  - Passing zero to the function to ensure the restore points
//    stack is completely empty in those points where you
//    expect this to be the case.
func (self *RendererUtils) AssertMaxRestorePoints(n int) {
	// ...
}
```

Example usage:
```Golang
// (inefficient and silly)
func (self *Game) Draw(canvas *ebiten.Image) {
	// some helper variables
	pad := int(ebiten.DeviceScaleFactor()*12)
	maxWidth := canvas.Bounds().Dx() - pad*2
	lineHeight := int(self.text.Utils().GetLineHeight())
	y := pad
	
	// draw chat messages
	for _, msg := range self.chatMessages {
		// draw username with custom format
		self.text.Utils().Memorize()
		msg.User.ApplyNameFormat(self.text)
		self.text.Draw(canvas, msg.User.Name, pad, int(y))
		y += lineHeight // lots of assumptions here
		self.text.Utils().Rewind()

		// draw message content with default format
		self.text.DrawWithWrap(canvas, msg.Content, pad, int(y), maxWidth)
		y += self.text.MeasureWithWrap(msg.Content, maxWidth).IntHeight()
 		y += pad/2

		if y >= canvas.Bounds().Dy() { break }
	}
}
```

It seems like a useful feature that could even be applied to some already existing examples, but I'm still thinking about a few details:
- Should we memorize scale or not? This one makes me uneasy because in general applications you would link the scale to the display scaling factor and you would like to keep it separated, logically independent from everything else. In practice, though, I can imagine quite a few scenarios where you may want to manipulate text scale on the fly while drawing, especially on games where we expect the UI to scale with the window, not the display scaling factor, and where we may have multiple UI areas with different "zoom levels". With ebitengine, the display scaling won't be changing concurrently ([won't be changing at all, actually](https://www.github.com/hajimehoshi/ebiten/issues/2343)), so memorizing the scale should be more practical and reasonable, but... it still bothers me.
- `AssertMaxRestorePoints()` is not strictly necessary at all, but I somehow want to communicate that it's easy to mess up and accidentally lose control of the size of the restore points stack. Alternatives include functions to set a size limit, functions to get the current stack size, or leaving it only at a couple lines of advice in the docs. Could also change the whole design to return a closing function or something altogether, but that seems way overkill.
- Implementation wise, there's the trivial "copy state into a struct, restore on rewind", but also the "store only deltas on a []uint8", which is more memory efficient and shouldn't get too slow either. The question is whether it is faster when dealing only with a couple modified fields (I'm always so lazy to benchmark).
- Names. I hate words. I don't like "save" and "restore" because it sounds like a videogame savepoint, and restoring doesn't sound like it should "destroy" (pop) the previous state, only bring you back there. Like, if I had to implement a second function for a non-destructive rewind, then I'd name *that* "restore". Of course "rewind" isn't that great either, but it's my least eww choice. Only bikeshedding here, don't mind me.

**Comment by kettek** [comment]
Looks well thought out and usable.

In regards to scale: I think it would be useful to store scale as well. In my own use-case I'll likely be applying the map's zoom to the text for visual sound effects (e.g., "*bonk*", "*scrape*", etc.). However, I am approaching this without much thought in regards to display scaling and how that would all interact. An approach to bypass this problem would be to have a DeviceScale separate from the regular Scale field -- global vs. local, effectively. Of course, I can just store my own local zoom levels and modify+restore the scale myself, so it's not critical.

In regards to copy state: Given how frequently the save/restores may happen, whichever is most performant would be the ideal choice, IMO. Deltas may introduce slower operations due to calculating them, even if they would provide better memory usage.

In regards to names: Memorize feels a bit clunky to me, but given that we're dealing with an engine/library intended for games, avoiding save is understandable. One could use a "store"/"restore" pair, which does logically fit, though perhaps not the clearest. It'd be the clearest to have something like "StoreState" + "RestoreState", but that's a bit verbose.

**Comment by tinne26** [comment]
Yeah, in the end I'm storing scale because there's plenty of perfectly reasonable use-cases for it.

If you don't like `Memorize()` / `Rewind()`, I think I'll switch to `StoreState()` / `RestoreState()` / `AssertMaxStoredStates()`. If we don't love any of the names anyway, better pick the most neutral option.

I already committed a sample implementation the other day, but I'll have to make broader changes so all restorable state is kept in a single struct that can be copied directly instead of field by field. I have too many individual checks right now due to trying to make the renderer's zero-value useful, but it's too much headache in too many parts of the code, so I'll be taking a different approach for that.

**Comment by kettek** [comment]
I would prefer `StoreState()`/ `RestoreState()` / `AssertMaxStoredStates()` for clarity.
